### ISSUE TITLE
Error loading testkit.sqf

### ISSUE THREAD

**Issue by SmokeyBR** [ebayShopper/TestKit#1]
There seems to be a problem with testkit.sqf with the given error.

**_18:49:34 "Res3tting B!S effects..."
18:49:36 Error in expression <
_caller = _value select 0;
_name = if (alive _caller) then {name _caller} else >
18:49:36   Error position: <alive _caller) then {name _caller} else >
18:49:36   Error alive: Type String, expected Object
18:49:36 File z\addons\dayz_server\init\testkit.sqf, line 21
18:49:37 "z\addons\dayz_code\system\REsec.sqf:Monitoring Remote Exe..."_**

also only when testkit enabled error on client side

**_Error in expression <z_thirst min SleepWater) max 0;
if (dayz_nutrition > 0) then {
_Nutrition = >
  Error position: <dayz_nutrition > 0) then {
_Nutrition = >
  Error Undefined variable in expression: dayz_nutrition
File z\addons\dayz_code\system\player_spawn_2.sqf, line 172
"player_forceSave called from fsm"_**

**Comment by ebaydayz** [comment]
You are using an outdated version. As you can see that line is not even in the current file:
https://github.com/ebaydayz/TestKit/blob/master/testkit.sqf

Please update to all the latest files on this git.

**Comment by ebaydayz** [comment]
Also the nutrition error should already be fixed in the current 1.0.6 Test Build. I haven't seen it in months, so please make sure you are fully updated on dayz_code, server and mission.

**Comment by SmokeyBR** [comment]
its all good, it was my bad for not getting the new files srry about that.
the nutrition problem would only occur with the outdated testkit enabled.
